[package]
name = "capuchin"
version = "0.2.0"
authors = ["Sean Kelly <code@katron.org>"]

[dependencies]
clap = "2.19.0"
csv = "1.0.0-beta.3"
error-chain = "0.10.0"
serde = "1.0.8"
serde_derive = "1.0.8"
